---
title: Bayesian Linear Regression
author: ''
date: '2018-05-11'
slug: bayesian-linear-regression
categories:
  - Bayesian Statistics
  - Linear Regression
tags: []
draft: true
---

This is the first in a series of posts on Bayesian linear regression with a proper prior. In this post I give an overview of the model and how to set up a proper prior distribution using expert knowledge. The next posts desrcibe how to sample the posterior using a Gibbs sampler and using Stan.

### The Model

In Bayesian linear regression, we model the data as

\[ Y = X\beta + \varepsilon, \hspace{10pt} \varepsilon|\sigma \sim N_n(0,\sigma^2I) \]


Here, $Y$ is the response and $X$ is the $n \times r$ matrix of covariates. We can write this model more compactly as

\[ Y|\beta,\tau \sim N_n\left(X\beta, \frac{1}{\tau} I\right). \]

In other words, we model $Y$ as multivariate normal with mean vector $X\beta$ and covariance matrix $\frac{1}{\tau}I$. This looks a lot like the classical linear regression model but the difference here is that we condition on $\beta$ and $\tau$ which are random variables instead of fixed values. We write $1 / \tau$ instead of $\sigma^2$ which is often done in Bayesian statistics because it makes some of the math easier.


## The Prior

Now that a model is specified for the data, we need to specify a prior distribution for the parameters. There is a lot of freedom here. We can use whatever prior  we think captures our prior information. However, we need to be able to obtain a sample from the posterior or we can't really do anything. Sometimes we use what's called an *improper* prior which is not actually a probabilty distribution but gives us a posterior that is. Here we consider a *proper* prior, so called because we specify a proper probability distribution. We use

\[ \beta \sim N_r(\beta_0, C), \hspace{10pt} \tau \sim \text{Gamma}(a,b). \]

Now comes the tricky part. So far we have specified the Normal/Gamma prior assuming we know the values of the parameters. Of course, we don't know the values but we need to specify them if we want to actually do anything. 

This is where we either need to have our own prior knowledge of the data at hand or have previous data we can use. Otherwise, we need to talk to an expert and try to get enough information out of them to specify the parameters. I consider this the hard case. The expert here is someone who knows about the underlying subject but may not have much knowledge of statistics, let alone Bayesian statistics. And even if they are well versed in Bayesian statistics, we can't exactly ask them what the covariance matrix is for $\beta$ or what the $a$ parameter is for $\tau$. So we need to ask our expert a series of questions, then use their answers to set values for $\beta_0, C, a$ and $b$.

## An Example

To illustrate what questions to ask the expert and how to turn the information into prior parameters, let's consider an example. The data we will use is on NBA players from the 2015 season. There are 28 variables but we will only consider 4 here. The response is personal fouls (PF) and we are going to model this as a function of steals (STL), blocks (BLK), and minutes (MIN): 

\[ PF|\beta,\tau \sim N(\beta_1 + \beta_2 STL + \beta_2 BLK + \beta_3 MIN, \hspace{5pt} 1/\tau) \]

These variables are recorded on a per game basis across the season (i.e. the first player had 0.6 personal fouls per game, 0.3 steals per game, 0 blocks, and played 12.4 minutes per game for the 2015 season).

```{r read_data, message = FALSE}
library(readr)
library(dplyr)
nba <- read_csv('../../static/data/nba2015.csv') %>%
  select(PF, STL, BLK, MIN)
nba
```

I don't really know anything about basketball so I had to consult with someone who does (my brother-in-law). There are various ways to obtain prior information. For the $\beta$s, I followed 



notes:

+ start with nba example
+ for induced prior equations
    - may not need all the equations
    - give $\tilde{X}$, etc. with values from questions
    - write transformations to turn into beta and tau








