---
title: What is Bayesian Statistics?
author: Andrew Bates
date: '2018-03-29'
slug: what-is-bayesian-statistics
categories:
  - Bayesian Statistics
tags: []
---

As of now I am in the middle of a Bayesian statistics course at San Diego State University. The course is interesting but one thing was particularly troubling when the course first started: I didn't know what made Bayesian statistics different from all the classical (or frequentist) courses I had taken previously. Hopefully this post will help clarify things for others who are just starting to learn about Bayesian statistics.

One of the reasons why it took me a while (a couple weeks) to understand the difference between Bayesian and frequentists statistics is that I could not find a satisfactory explanation online. I did find a number of posts, lecture notes, etc. that tried to explain the difference but they didn't really help that much. Most of them either said something along the lines of "the difference is in the interpretation of probability", or gave some sort of explanation through a specific example without any math/stats (which is almost never helpful for me), or just explained Bayes rule in the discrete case (which is not exclusive to Bayesian statistics). These approaches are not necessarily wrong, I just felt they were too simplified for someone like me who has a math and stats background.

### They Bayesian Approach

To remedy this, I would like to give my idea of the difference between Bayesian and frequentist statistics. For me, the difference is easiest to understand with the following table:

|           | Bayesian  | Frequentist |
|:---------:|:---------:|:-----------:|
| parameter | random    | fixed       |
| data      | fixed     | random      |

To elaborate, given a model for the data, a frequentist views the parameters of that model to be some fixed (but unknown) value and the data to come from a random variable. The view is that the data will be generated by some model with a given value for the parameters. The randomness comes from the data itself as each sample we take will be different.

A Bayesian takes sort of the opposite approach. Like a frequentist, the data is viewed as coming from a model with a set of parameters. But the difference is that the parameters of the model are considered random and the data is viewed as fixed once it is observed.

To me, this is the fundamental difference between the classical and Bayesian approaches: how parameters and data are treated. The common explanations I mentioned above don't capture this. One is more of a philosophical difference and the others, although they may be useful for some, are too simplified and I don't think they really add anything to what a first course in probability or statistics would cover.

This difference imparts an approach to Bayesian and frequentist inference. In the frequentist world, we want to estimate the parameter (a fixed value) along with a confidence interval and maybe a p-value. We then use that estimate to infer the model for the population. In the Bayesian context, we want to find the (new) distribution of the parameter, given the data. This lets us infer how our parameter has changed based on the data and gives us a current, updated estimate.

### An Example

To illustrate the Bayesian approach, let's consider a simple example: Binomial data. Suppose a single data point that is Binomial with parameters $n$ and $p$ where $n$ is known (this is the same as $n$ Bernoulli data points). In the Bayesian approach, we consider $p$ to be a random variable. To make the math easier, we consider $p$ to follow a Beta distribution. Note that this is not necessary, $p$ could have whatever distribution we want as long as it meets the conditions for a Binomial (between 0 and 1). We write this model as follows:

\[X| p \sim \mathrm{Binomial}(n,p) \]
where
\[ p \sim \mathrm{Beta}(a,b). \]

The first line is the model for the data and the second is the model for the $p$. The distribution for $p$ is called the *prior distribution* (remember that we know $n$ here). The parameters $a$ and $b$ for $p$ are chosen independently of viewing the data based on an expert opinion (we won't get into how to do that here). What we are interested in is finding the *posterior distribution* of $p$ given the data. That is, we want to find $f(p|X_1, \ldots, X_n)$. This will give us insight into how $p$ behaves and can be used as the prior distribution for a future data analysis.

Because we chose the distribution for $p$ to be a beta, its not too difficult to find the posterior. We just need to invoke Bayes rule (this is a generalization of Bayes rule in the discrete case):

\[ f(p|X) = \frac{f(X|p)f(p)}{\int_0^1f(X|p)f(p) \hspace{3pt} dp}. \]
 
It turns out we can simplify the above expression because the denominator is just a normalizing constant to ensure the density integrates to 1. We can also simplify by ignoring the constants for each of the densities. We only need to figure out what is called the kernel of the density because this is enough to tell us the distribution. So we can find the posterior as follows:

\begin{align*}
f(p|X) &\propto p^x(1-p)^{n-x}  p^{a-1} (1-p)^{b-1} \\
&= p^{(x+a)-1}(1-p)^{(n-x+b)-1}.
\end{align*}

This looks like a Beta distribution with parameters $x+a$ and $n-x+b$. We could have worked this out by putting in all the distribution constants and evaluating the integral but its a lot easier not to and the math can be done to show why that is o.k.


### Summary

To reiterate, I think the difference between the Bayesian and frequentist approach to statistics boils down to how the data and parameters of a model are treated (fixed vs. random). I also think it's easier to understand the difference in this way particularly for someone who already knows a bit about statistics. Hopefully this post will help to clarify things for those who end up in a similar situation as I was in.

